name: Run Python Script

on:
  schedule:          # 定时任务 第一个填分钟 第二个填小时
    - cron:  0 7 * * *   # 想要运行的小时-8即为填入值例如：bj11点运行 填11-8=3

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install Selenium
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=127.0.6533.88
        wget 	https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.88/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        chromedriver --version

    - name: Clone repository
      run: |
        git clone https://github.com/Sixfeet6/zkg.git
        cd zkg

    - name: Run Python script
      run: |
        cd zkg
        python 1.py
